feat: add precommit lint

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -26,12 +26,12 @@ pnpm run check-format ||
 #     exit 1; 
 # }
 
-# echo '📘 Checking TypeScript types...'
-# pnpm run check-types ||
-# {
-#     echo '❌ Type check failed. Please fix TypeScript errors.';
-#     exit 1;
-# }
+echo '📘 Checking TypeScript types...'
+pnpm run check-types ||
+{
+    echo '❌ Type check failed. Please fix TypeScript errors.';
+    exit 1;
+}
 
 # If everything passes... Now we can commit
 echo '✅ All checks passed! Committing now...'
